apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-api
  description: Сервис централизованного хранения proto контрактов
  annotations:
    github.com/project-slug: s21platform/user-proto  # Укажите правильный репозиторий
#    backstage.io/techdocs-ref: dir:.  # Если планируете использовать TechDocs
  tags:
    - proto
spec:
  type: grpc
  lifecycle: production
  owner: user-service-team  # GitHub-логин ответственного
  definition: url:https://github.com/s21platform/user-proto/user.proto  # Путь к файлу proto-схемы
#  providesApis:
#    - user-api  # API, который предоставляет сервис
#  consumesApis:
#    - community-api
#    - optionhub-api
#  dependsOn:
#    - component:community
#    - component:optionhub
#  system: authentication-system  # Можно указать систему, если есть